"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Auto-discover and load plugins
def load_plugins():
    """Automatically discovers and returns plugins in the plugins folder (both plugins/ and plugins/downloader/)"""
    discovered = []
    
    try:
        plugins_dir = BASE_DIR / 'plugins'
        
        # Check if plugins directory exists
        if not plugins_dir.exists():
            return discovered
        
        # Manually discover plugins to avoid import issues
        import json
        
        def discover_plugin(plugin_dir, base_path='plugins'):
            """Discover a single plugin"""
            # Skip hidden directories and __pycache__
            if not plugin_dir.is_dir() or plugin_dir.name.startswith('_'):
                return None
            
            # Check if plugin.json exists
            plugin_json = plugin_dir / 'plugin.json'
            if not plugin_json.exists():
                return None
            
            # Validate plugin.json
            try:
                with open(plugin_json, 'r', encoding='utf-8') as f:
                    config = json.load(f)
                
                # Check required fields
                plugin_name = config.get('name')
                if not plugin_name:
                    return None
                
                # Check if plugin has required files (urls.py or views.py)
                # This ensures it's a valid Django app
                has_urls = (plugin_dir / 'urls.py').exists()
                has_views = (plugin_dir / 'views.py').exists()
                
                if not (has_urls or has_views):
                    # Plugin might not be a Django app, skip
                    return None
                
                # Add to discovered plugins with correct path
                plugin_app_path = f'{base_path}.{plugin_dir.name}'
                return plugin_app_path
                
            except (json.JSONDecodeError, Exception) as e:
                # Skip invalid plugins
                print(f"Warning: Skipping invalid plugin {plugin_dir.name}: {e}")
                return None
        
        # 1. Find plugins in the main plugins/ folder
        for plugin_dir in plugins_dir.iterdir():
            if plugin_dir.name == 'downloader':
                continue  # Skip downloader directory itself
            
            plugin_app_path = discover_plugin(plugin_dir, 'plugins')
            if plugin_app_path:
                discovered.append(plugin_app_path)
        
        # 2. Find plugins in the plugins/downloader/ folder
        downloader_dir = plugins_dir / 'downloader'
        if downloader_dir.exists() and downloader_dir.is_dir():
            for plugin_dir in downloader_dir.iterdir():
                plugin_app_path = discover_plugin(plugin_dir, 'plugins.downloader')
                if plugin_app_path:
                    discovered.append(plugin_app_path)
        
    except Exception as e:
        # If plugin system is not available, return empty list
        print(f"Warning: Could not load plugins: {e}")
        import traceback
        traceback.print_exc()
    
    return discovered

# Discover plugins automatically
DISCOVERED_PLUGINS = load_plugins()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'sdgdsaghdsf54541asd-c)w0q@)zh48rh1$0hb*il^+887s@u6m*kpp2tj-q(a2k-p!ap2')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost,0.0.0.0').split(',')

# Prevent Django from redirecting missing-trailing-slash URLs (causes 301 for files)
APPEND_SLASH = True


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be at the top for Channels
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # WebSocket support
    'common.profile',
    'common.security',
    'common.smtp',  # SMTP Email Automation module
    'modul.process_monitor',  # Process Monitor module
    'modul.system_information',  # System Information module
    'modul.SystemLogs',  # System Logs module
    'modul.docker_manager',  # Docker Manager module
    'modul.service_monitoring',  # Service Monitoring module
    'modul.process_topology',  # Process Topology module
    'modul.service_builder',  # Service Builder module
    'modul.user_management',  # User Management module
    'modul.firewall',  # Firewall Management module
    'modul.package_manager',  # Package Manager module
    'modul.dev_packages',  # Developer Packages module
    'modul.cve_scanner',  # CVE Scanner module
    'common.dashboard',  # Dashboard module
    'plugins',  # Plugin system
    # Plugins are loaded automatically (by plugins/loader.py)
] + DISCOVERED_PLUGINS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.UserLanguageMiddleware',  # Load user's preferred language
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.request_logging.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'plugins.context_processors.plugins_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('tr', 'Türkçe'),
    ('de', 'Deutsch'),
]

# Locale paths
LOCALE_PATHS = [
    BASE_DIR / 'locale',
    # Plugin locale paths will be added dynamically
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise static file storage for production
STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'

# WhiteNoise settings for production
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True
WHITENOISE_MANIFEST_STRICT = False

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# IP Geolocation removed

# CSRF and security settings
CSRF_USE_SESSIONS = True
CSRF_COOKIE_HTTPONLY = True

if DEBUG:
    # Development: allow HTTP and common local origins
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost',
        'http://127.0.0.1',
    ]
else:
    # Production: enforce HTTPS and restrict origins
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'Lax'  # Consider 'Strict' if it fits your flows
    # Set trusted origins via env (comma-separated), e.g. "https://example.com,https://admin.example.com"
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# ===== CHANNELS / WEBSOCKET CONFIGURATION =====

# ASGI Application
ASGI_APPLICATION = 'core.asgi.application'

# Channel Layers - In-Memory (Development) / Redis (Production)
if DEBUG:
    # Development: In-Memory Channel Layer (sufficient for single worker)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    # Production: Redis Channel Layer (multi-worker support)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379/0')],
            },
        },
    }
